name: deploy member-service

on:
  push:
    branches:
      - main
    paths:
      - "3.msa/member/**"
      - ".github/workflows/deploy_member_with_k8s.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v2

      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"
        id: install

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ap-northeast-2

      - name: update cluster infomation
        run: aws eks update-kubeconfig --name my-cluster --region ap-northeast-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: build and push docker image to ecr
        env:
          REGISTRY: 895421295243.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: member-service
          IMAGE_TAG: latest
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -f ./3.msa/member/Dockerfile ./3.msa/member
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: eks kubectl apply and restart
        run: |
          kubectl apply -f ./3.msa/member/k8s/depl_svc.yml
          kubectl rollout restart deployment member-depl -n soldesk